version: '3.9'

services:
  backend:
    container_name: dailycheckapp_backend_app
    build: .
    ports:
      - '3000:3000' 
    environment:
      PGUSER: 'docker'
      PGPASSWORD: '123456'
      PGHOST: 'db'
      PGDATABASE: 'postgres'     
  db:
    container_name: dailycheckapp_database
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: